name: Lighthouse Performance

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Start server
      run: |
        # Find an available port
        PORT=$(python3 -c "import socket; s=socket.socket(); s.bind(('', 0)); print(s.getsockname()[1]); s.close()")
        echo "Using port: $PORT"
        echo "LIGHTHOUSE_PORT=$PORT" >> $GITHUB_ENV
        
        # Start server in background
        python3 -m http.server $PORT &
        SERVER_PID=$!
        echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
        
        # Wait for server to be ready
        timeout 30 bash -c "until curl -s http://localhost:$PORT > /dev/null; do sleep 1; done"
        echo "Server is ready on port $PORT"

    - name: Run Lighthouse CI
      run: |
        npm install -g @lhci/cli
        lhci autorun --config=./lighthouserc.js
      env:
        LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.sha }}

    - name: Stop server
      if: always()
      run: |
        if [ ! -z "$SERVER_PID" ]; then
          kill $SERVER_PID || true
        fi
